# Generated by Django 6.0.3 on 2026-03-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=100)),
                ("memory", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                (
                    "price_ordinary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_promotional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("product_code", models.CharField(max_length=100, unique=True)),
                ("number_of_reviews", models.IntegerField(default=0)),
                ("screen_diagonal", models.CharField(max_length=100)),
                ("display_resolution", models.CharField(max_length=100)),
                ("characteristics", models.JSONField()),
                ("images", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
