# Generated by Django 6.0.3 on 2026-03-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parser",
            name="number_of_reviews",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
